AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: {{ cookiecutter.project_name }}

Resources:

  {{ cookiecutter.aws_lambda_resource_name }}:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: {{ cookiecutter.function_name }}
      Architectures: 
        - {{ cookiecutter.architecture }}
      Runtime: java11
      MemorySize: 128
      Handler: {{ cookiecutter.java_package_name }}.{{ cookiecutter.java_class_name }}::{{ cookiecutter.java_handler_method_name }}
      CodeUri: target/{{ cookiecutter.project_name }}.jar
      Timeout: {{ cookiecutter.timeout }}
      Tracing: {{ cookiecutter.tracing }}
